create table app_user (enabled boolean not null, role tinyint check ((role between 0 and 2)), id bigint generated by default as identity, email varchar(255), password varchar(255), username varchar(255), primary key (id), unique (username, email));
create table task (created_at timestamp(6) not null, id bigint generated by default as identity, updated_at timestamp(6), user_id bigint not null, title varchar(100) not null, description varchar(500), status enum ('CANCELLED','COMPLETED','IN_PROGRESS','PENDING') not null, primary key (id));
create index idx_email on app_user (email);
alter table if exists task add constraint FKsh6s1t7gbjr0ja7923du08fi8 foreign key (user_id) references app_user;
